# Generated by Django 4.1.2 on 2022-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitflyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycandlesticks',
            name='close_time',
            field=models.FloatField(unique=True),
        ),
    ]
