# Generated by Django 4.1.2 on 2022-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitflyer', '0002_alter_daycandlesticks_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycandlesticks',
            name='close_price',
            field=models.FloatField(default=0.0),
        ),
    ]
